root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  include_ext = ["templ"]
  cmd = "templ generate"
  follow_symlink = false
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true
