root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  delay = 1000
  kill_delay = 10
  include_ext = ["go"]
  cmd = "go test ./tests/... -v"
  exclude_unchanged = false
  follow_symlink = false
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true
