root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  include_ext = ["go", "html", "sql", "js", "css"]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ./cmd/main.go"
  exclude_unchanged = false
  follow_symlink = false
  full_bin = "export $(grep -v '^#' .env | xargs); ./tmp/main"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true
