// Code generated by templ - DO NOT EDIT.

// templ: version: 0.2.476
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Leftpanel() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<aside class=\"bg-backgroundalt text-text absolute z-10 min-h-screen w-fit -translate-x-full transform transition-transform duration-500\" hx-ext=\"receiver\" on-event:menu-open=\"\n      this.classList.remove(&#39;-translate-x-full&#39;);\n      this.classList.add(&#39;translate-x-0&#39;);\n      this.querySelectorAll(&#39;button&#39;).forEach((el) =&gt; {\n        toggleTabIndex(el);\n      });\n      this.querySelectorAll(&#39;a&#39;).forEach((el) =&gt; {\n        toggleTabIndex(el);\n      });\n    \" on-event:menu-close=\"\n      this.classList.remove(&#39;translate-x-0&#39;);\n      this.classList.add(&#39;-translate-x-full&#39;);\n      this.querySelectorAll(&#39;button&#39;).forEach((el) =&gt; {\n        toggleTabIndex(el);\n        el.blur();\n      });\n      this.querySelectorAll(&#39;a&#39;).forEach((el) =&gt; {\n        toggleTabIndex(el);\n        el.blur();\n      });\n    \"><div class=\"flex items-center justify-start gap-2 p-2 text-2xl\"><button class=\"text-accent p-2\" aria-label=\"Close menu\" hx-on:click=\"emit(&#39;menu-close&#39;);\" class=\"p-2\" tabindex=\"-1\" hx-ext=\"receiver\" on-event:menu-open=\"\n          this.focus();\n        \"><!--")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var2 := ` menu left icon `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("--><svg stroke=\"currentColor\" fill=\"currentColor\" stroke-width=\"0\" viewBox=\"0 0 24 24\" height=\"1em\" width=\"1em\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M21 17.9995V19.9995H3V17.9995H21ZM6.59619 3.90332L8.01041 5.31753L4.82843 8.49951L8.01041 11.6815L6.59619 13.0957L2 8.49951L6.59619 3.90332ZM21 10.9995V12.9995H12V10.9995H21ZM21 3.99951V5.99951H12V3.99951H21Z\"></path></svg></button> <a href=\"/\" class=\"flex items-center justify-center p-2\" tabindex=\"-1\" aria-label=\"Home\"><svg stroke=\"currentColor\" fill=\"currentColor\" stroke-width=\"0\" viewBox=\"0 0 24 24\" height=\"1em\" width=\"1em\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M12.97 2.59a1.5 1.5 0 0 0-1.94 0l-7.5 6.363A1.5 1.5 0 0 0 3 10.097V19.5A1.5 1.5 0 0 0 4.5 21h4.75a.75.75 0 0 0 .75-.75V14h4v6.25c0 .414.336.75.75.75h4.75a1.5 1.5 0 0 0 1.5-1.5v-9.403a1.5 1.5 0 0 0-.53-1.144l-7.5-6.363Z\"></path></svg></a> <a href=\"/dashboard\" class=\"flex items-center justify-center p-2\" tabindex=\"-1\" aria-label=\"Dashboard\"><svg stroke=\"currentColor\" fill=\"currentColor\" stroke-width=\"0\" viewBox=\"0 0 24 24\" height=\"1em\" width=\"1em\" xmlns=\"http://www.w3.org/2000/svg\"><path fill=\"none\" d=\"M0 0h24v24H0z\"></path> <path d=\"M11 21H5c-1.1 0-2-.9-2-2V5c0-1.1.9-2 2-2h6v18zm2 0h6c1.1 0 2-.9 2-2v-7h-8v9zm8-11V5c0-1.1-.9-2-2-2h-6v7h8z\"></path></svg></a></div></aside>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
